name: build yup toolchain

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: setup LLVM 14
      run: cd yupc && chown "$USER" ./llvm.sh && chmod u+x ./llvm.sh && sudo ./llvm.sh 14
      
    - name: generate ANTLR4 files
      run: cd yupc && chmod u+x ./gen.sh && ./gen.sh
      
    - name: build yupc
      run: cd yupc && chmod u+x ./build.sh && ./build.sh
      
